background="#1e1e2e"
text="#cdd6f4"
subtle="#a6adc8"
warning-text="#f38ba8"
text-special-one="#b4befe"
text-special-two="#a6e3a1"
top-bar-background="#181825"
top-bar-text="#cdd6f4"
status-bar-background="#181825"
status-bar-text="#cdd6f4"
status-bar-view-background="#181825"
status-bar-view-text="#cdd6f4"
command-text="#cdd6f4"
list-selected-background="#74c7ec"
list-selected-text="#6c7086"
list-selected-inactive-background="#313244"
list-selected-inactive-text="#cdd6f4"
controls-text="#cdd6f4"
controls-highlight="#a6e3a1"
autocomplete-background="#181825"
autocomplete-text="#cdd6f4"
autocomplete-selected-background="#b4befe"
autocomplete-selected-text="#45475a"
button-color-one="#74c7ec"
button-color-two="#45475a"
timeline-name-background="#181825"
timeline-name-text="#cdd6f4"
