-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
  return {
    kind = {
      Array = "",
      Boolean = "",
      Class = "",
      Color = "",
      Constant = "",
      Constructor = "",
      Enum = "",
      EnumMember = "",
      Event = "",
      Field = "",
      File = "",
      Folder = "󰉋",
      Function = "",
      Interface = "",
      Key = "",
      Keyword = "",
      Method = "",
      Module = "",
      Namespace = "",
      Null = "󰟢",
      Number = "",
      Object = "",
      Operator = "",
      Package = "",
      Property = "",
      Reference = "",
      Snippet = "",
      String = "",
      Struct = "",
      Text = "",
      TypeParameter = "",
      Unit = "",
      Value = "",
      Variable = "",
    },
    type = {
      Array = "󰅨",
      Boolean = "",
      Number = "",
      Object = "",
      String = "󰅳",
    },
    documents = {
      File = "",
      Files = "",
      Folder = "",
      OpenFolder = "",
    },
    git = {
      Add = "",
      Deleted = "",
      Diff = "",
      Ignore = "",
      Mod = "",
      Remove = "",
      Rename = "",
      Repo = "",
      Staged = "S",
      Unmerged = "",
      Unstaged = "",
      Untracked = "U",
    },
    ui = {
      ArrowCircleDown = "",
      ArrowCircleLeft = "",
      ArrowCircleRight = "",
      ArrowCircleUp = "",
      BigCircle = "",
      BigUnfilledCircle = "",
      BoldArrowDown = "",
      BoldArrowLeft = "",
      BoldArrowRight = "",
      BoldArrowUp = "",
      BoldClose = "",
      BoldDividerLeft = "",
      BoldDividerRight = "",
      BoldLineLeft = "▎",
      BookMark = "",
      BoxChecked = "",
      Lock = "",
      Bug = "",
      Calendar = "",
      Check = "",
      ChevronRight = ">",
      Circle = "",
      Close = "",
      Code = "",
      Comment = "󰅺",
      Dashboard = "",
      Fire = "",
      Gear = "",
      History = "",
      Lightbulb = "",
      LineLeft = "▏",
      LineMiddle = "│",
      List = "",
      NewFile = "",
      Note = "",
      Package = "",
      Pencil = "",
      Project = "",
      Search = "",
      SignIn = "",
      Table = "",
      Telescope = "",
    },
    diagnostics = {
      Error = "",
      Hint = "",
      Information = "",
      Question = "",
      Warning = "",
    },
    misc = {
      Robot = "ﮧ",
      Squirrel = "",
      Tag = "",
      Watch = "",
    },
  }
